development:
  adapter: postgresql
  database: spam
  username: _postgresql

test:
  adapter: sqlite3
  database: db/db.sqlite3

production:
  adapter: postgresql
  database: spam
  username: _postgresql

demo_development:
  adapter: postgresql
  database: spamdemo
  username: guest

demo_production:
  adapter: postgresql
  database: spamdemo
  username: guest
